
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  mapperLocations: classpath:/com.hp.multidatatest.data.mappers/*.xml
  write:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver
     minIdle: 5
     maxActive: 100
     initialSize: 10
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 50
     removeAbandoned: true
     filters: stat
  reads[0]:
     url: jdbc:mysql://127.0.0.1:3306/test_01?useUnicode=true&amp;characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver
     minIdle: 5
     maxActive: 100
     initialSize: 10
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 50
     removeAbandoned: true
     filters: stat
  reads[1]:
     url: jdbc:mysql://127.0.0.1:3306/test_02?useUnicode=true&amp;characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver
     minIdle: 5
     maxActive: 100
     initialSize: 10
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 50
     removeAbandoned: true
     filters: stat
  reads[2]:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver
     minIdle: 5
     maxActive: 100
     initialSize: 10
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 50
     removeAbandoned: true
     filters: stat
server:
  port: 8011